# -*- coding: utf-8 -*-
"""Ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJZViJpCrDbthP6xBu2ZRKRKRrTVTtgC

Inceputuri

# Colectarea de date
"""

import requests
import pandas as pd
import time
import random

api_key = "5ae2e3f221c38a28845f05b6d39ea85b65163d209754a67b5f62156e"

orase = ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Constanta",
         "Brasov", "Oradea", "Sibiu", "Targu Mures", "Craiova", "Galati", "Suceava"]

toate_locatiile = []

for oras in orase:
    print(f"📍 Caut în {oras}")

    geo = requests.get(
        f"https://api.opentripmap.com/0.1/en/places/geoname?name={oras}&apikey={api_key}"
    ).json()

    lat, lon = geo.get("lat"), geo.get("lon")

    if not lat or not lon:
        print(f"⚠️ Nu am găsit coordonate pentru {oras}. Sar peste...")
        continue

    radius_url = f"https://api.opentripmap.com/0.1/en/places/radius?radius=10000&lon={lon}&lat={lat}&limit=100&apikey={api_key}"
    features = requests.get(radius_url).json().get("features", [])

    for f in features:
        xid = f["properties"]["xid"]
        detail_url = f"https://api.opentripmap.com/0.1/en/places/xid/{xid}?apikey={api_key}"
        detail = requests.get(detail_url).json()

        if not detail.get("name"):
            continue

        rate = detail.get("rate", "")
        popularitate = {"3h": 3, "2h": 2, "1h": 1}.get(rate, 0)

        rating_general = round(random.uniform(3.5, 5.0), 1)
        nr_recenzii = random.randint(50, 3000)

        categorii = detail.get("kinds", "")
        categorie = categorii.split(",")[0].replace("_", " ").capitalize() if categorii else "Necunoscut"
        categorie_lc = categorie.lower()

        # Sezon
        if "beaches" in categorie_lc or "coast" in categorie_lc:
            sezon = "Cald"
        elif "ski" in categorie_lc or "mountain" in categorie_lc:
            sezon = "Rece"
        elif "museum" in categorie_lc or "architecture" in categorie_lc:
            sezon = "Oricând"
        else:
            sezon = random.choice(["Cald", "Rece", "Oricând"])

        # Pret estimativ
        if "museum" in categorie_lc:
            pret = random.randint(20, 60)
        elif "amusement" in categorie_lc:
            pret = random.randint(50, 100)
        elif "thermal" in categorie_lc or "spa" in categorie_lc:
            pret = random.randint(70, 150)
        elif "park" in categorie_lc or "nature" in categorie_lc:
            pret = 0
        elif "religious" in categorie_lc or "monastery" in categorie_lc:
            pret = random.choice([0, 10])
        else:
            pret = random.randint(10, 50)

        if pret == 0:
            pret_categorie = "Gratuit"
        elif pret <= 30:
            pret_categorie = "Mic"
        elif pret <= 70:
            pret_categorie = "Mediu"
        else:
            pret_categorie = "Mare"

        # Tip calatorie
        if any(kw in categorie_lc for kw in ["museum", "architecture", "urban"]):
            tip_calatorie = "City Break"
        elif any(kw in categorie_lc for kw in ["park", "nature", "mountain", "lake"]):
            tip_calatorie = "Relaxare"
        elif any(kw in categorie_lc for kw in ["thermal", "spa", "amusement", "beach"]):
            tip_calatorie = "Relaxare"
        elif any(kw in categorie_lc for kw in ["historic", "religious", "monastery"]):
            tip_calatorie = "Circuit"
        else:
            tip_calatorie = random.choice(["City Break", "Circuit", "Relaxare"])

        # Durata minima (numerică)
        if tip_calatorie == "City Break":
            durata_minima = 1
        elif tip_calatorie == "Circuit":
            durata_minima = 5
        else:
            durata_minima = 2

        # Cuvinte cheie pentru locație
        cuvinte_cheie = []

        if "religion" in categorie_lc:
            cuvinte_cheie = ["religios", "spiritual", "biserică", "mănăstire", "credință",]
        elif "historic architecture" in categorie_lc:
            cuvinte_cheie = [ "clădiri vechi", "monumente istorice", "istorie", "patrimoniu"]
        elif "historic" in categorie_lc:
            cuvinte_cheie = ["istoric", "cultură", "evenimente istorice", "istorie"]
        elif "cinemas" in categorie_lc:
            cuvinte_cheie = ["cinema", "film",  "sală de cinema", "evenimente cinematografice"]
        elif "cultural" in categorie_lc:
            cuvinte_cheie = ["cultură", "arte", "expoziție", "festival", "evenimente culturale", "muzică", "dans"]
        elif "other" in categorie_lc:
            cuvinte_cheie = ["diverse", "locație", "interesant", "explorare", "necategorizat", "activități diverse"]
        elif "museums" in categorie_lc:
            cuvinte_cheie = ["muzeu", "expoziție", "artă", "istorie", "cultură"]
        elif "architecture" in categorie_lc:
            cuvinte_cheie = ["arhitectură", "design", "clădiri", "structuri", "construcții", ]
        elif "fountains" in categorie_lc:
            cuvinte_cheie = ["fântână", "apă", "fontană", "loc de relaxare", "jocuri de apă"]
        elif "palaces" in categorie_lc:
            cuvinte_cheie = ["palat", "monarhie", "regal", "eleganță", "lux"]
        elif "theatres and entertainments" in categorie_lc:
            cuvinte_cheie = ["teatru", "spectacol", "muzică", "dans", "entertainment", "divertisment"]
        elif "towers" in categorie_lc:
            cuvinte_cheie = ["turn", "vârf", "panoramă", "priveliște"]
        elif "cemeteries" in categorie_lc:
            cuvinte_cheie = ["cemetery", "mormânt", "istorie", "cultură", "spiritualitate"]
        elif "biographical museums" in categorie_lc:
            cuvinte_cheie = ["muzeu biografic", "viața unui om"]
        elif "fortifications" in categorie_lc:
            cuvinte_cheie = ["fortificație", "castel", "cetate"]
        elif "urban environment" in categorie_lc:
            cuvinte_cheie = ["urban", "oraș", "străzi", "viață urbană"]
        elif "gardens and parks" in categorie_lc:
            cuvinte_cheie = ["grădina", "parc", "natură", "relaxare", "plimbare"]
        elif "view points" in categorie_lc:
            cuvinte_cheie = ["priveliște", "panoramă", "peisaj"]
        elif "science museums" in categorie_lc:
            cuvinte_cheie = ["muzeu științific", "inovație", "tehnologie", "descoperire", "experimente", "invenții"]
        elif "settlements" in categorie_lc:
            cuvinte_cheie = ["așezare", "comunitate", "village", "oraș", "istorie", "cultura locală"]
        elif "natural" in categorie_lc:
            cuvinte_cheie = ["natură", "conservare", "peisaj natural", "faună", "floră"]
        elif "beaches" in categorie_lc:
            cuvinte_cheie = ["plajă", "soare", "vacanță", "relaxare", "mare", "ocean", "nisip"]
        elif "geological formations" in categorie_lc:
            cuvinte_cheie = ["forme geologice", "munte", "caverne", "peșteri"]
        elif "battlefields" in categorie_lc:
            cuvinte_cheie = ["câmp de bătălie", "istorie militară", "război"]
        elif "bridges" in categorie_lc:
            cuvinte_cheie = ["pod", "construcție", "istoric"]
        else:
            cuvinte_cheie = ["locație", "descoperire", "activități diverse"]

        location = {
            "oras": oras,
            "denumire": detail.get("name"),
            "categorie": categorie,
            "rating_general": rating_general,
            "nr_recenzii": nr_recenzii,
            "pret_categorie": pret_categorie,
            "sezon": sezon,
            "tip_calatorie": tip_calatorie,
            "durata_minima": durata_minima,
            "cuvinte_cheie": cuvinte_cheie,
        }
        toate_locatiile.append(location)
        time.sleep(1)  # Respectă limita de API (maxim 1 cerere pe secundă)

# Crează DataFrame din lista de locații
df_locatii = pd.DataFrame(toate_locatiile)

# Salvează în format CSV
df_locatii.to_csv("locatii_turistice.csv", index=False)

# Afișează primele 5 locații
print(df_locatii.head())

"""# Normalizarea și preprocesarea datelor:"""

import pandas as pd

df = pd.read_csv("locatii_turistice.csv")
df.head()

"""### Verifificarea si tratarea datelor null"""

df.isnull().sum() #numar cate date sunt null

df=df.dropna()
df.isnull().sum()
# sterg datele nulll si verific daca mai am altele

"""## Tratarea duplicatelor"""

print(df.duplicated())  # Afișează un True pentru rândurile duplicate

"""## Standardizarea"""

print(df['categorie'].unique())  # Afișează valorile unice din coloana 'categorie'
print(df['tip_calatorie'].unique())  # Afișează valorile unice din coloana 'tip_calatorie'

"""## Detectarea și Tratarea Valorilor Aberante"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Calcularea IQR pentru coloana 'rating_general'
Q1 = df['rating_general'].quantile(0.25)
Q3 = df['rating_general'].quantile(0.75)
IQR = Q3 - Q1

# Definirea limitelor pentru valorile aberante
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Detectarea valorilor aberante
outliers = df[(df['rating_general'] < lower_bound) | (df['rating_general'] > upper_bound)]

print("Valorile aberante identificate:", outliers)

"""## Transformam String in Numere

### ~TF-IDF cuvinte cheie (dar cred ca o sa ma razgandesc)~
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
import nltk
from nltk.stem import WordNetLemmatizer

# Asigură-te că ai descărcat resursele necesare pentru lemmatizare
nltk.download('wordnet')
nltk.download('omw-1.4')

# Inițializează lemmatizatorul
lemmatizer = WordNetLemmatizer()

# Cuvinte cheie pentru fiecare categorie
categorii = {
    "religion": ["religios", "spiritual", "biserică", "mănăstire", "credință"],
    "historic architecture": ["clădiri vechi", "monumente istorice", "istorie", "patrimoniu"],
    "cinemas": ["cinema", "film", "sală de cinema", "evenimente cinematografice"],
    "historic": ["istorie", "cultură", "evenimente istorice", "istorie"],
    "cultural": ["cultură", "arte", "expoziție", "festival", "evenimente culturale", "muzică", "dans"],
    "other": ["diverse", "locație", "interesant", "explorare", "necategorizat", "activități diverse"],
    "museums": ["muzeu", "expoziție", "artă", "istorie", "cultură"],
    "architecture": ["arhitectură", "design", "clădiri", "structuri", "construcții"],
    "fountains": ["fântână", "apă", "fontană", "loc de relaxare", "jocuri de apă"],
    "palaces": ["palat", "monarhie", "istorie", "eleganță", "lux"],
    "theatres and entertainments": ["teatru", "spectacol", "muzică", "dans", "entertainment", "divertisment", "cultură"],
    "towers": ["turn", "vârf", "panoramă", "priveliște"],
    "cemeteries": ["cemetery", "mormânt", "istorie", "cultură", "spiritualitate"],
    "biographical museums": ["muzeu biografic", "viața unui om"],
    "fortifications": ["fortificație", "castel", "cetate", "istorie"],
    "urban environment": ["urban", "oraș", "viață urbană"],
    "gardens and parks": ["grădina", "parc", "natură", "relaxare", "plimbare"],
    "view points": ["priveliște", "panoramă", "peisaj", "natură"],
    "science museums": ["muzeu stiințific", "inovație", "tehnologie", "descoperire", "experimente", "invenții"],
    "settlements": ["așezare", "comunitate", "village", "oraș", "istorie", "cultura locală"],
    "natural": ["natură", "conservare", "peisaj natural", "faţă", "floră"],
    "beaches": ["plajă", "soare", "vacanță", "relaxare", "mare", "ocean", "nisip", "natură"],
    "geological formations": ["forme geologice", "munte", "caverne", "peșteri", "natură"],
    "battlefields": ["câmp de bătălie", "istorie militară", "război", "istorie"],
    "bridges": ["pod", "construcție", "istorie"]
}

# Funcție de preprocesare pentru a elimina stopwords și a lemmatiza cuvintele
def preprocesare(text):
    # Lemmatizează fiecare cuvânt din text
    text = ' '.join([lemmatizer.lemmatize(word) for word in text.split() if word not in ENGLISH_STOP_WORDS])
    return text

# Preprocesarea datelor: combină toate categoriile într-un corpus de text
corpus = [' '.join(cuvinte) for cuvinte in categorii.values()]
corpus = [preprocesare(text) for text in corpus]

# Verifică corpusul pentru a observa ce conține
print("Corpusul preprocesat:")
print(corpus)

# Crearea vectorului TF-IDF cu parametrii ajustați
vectorizer = TfidfVectorizer(stop_words=None, ngram_range=(1, 2), max_df=0.85)
X = vectorizer.fit_transform(corpus)

print("\nCorpusul după preprocesare:")
print(corpus)


# Afișarea vocabularului (cuvintele unice extrase din corpus)
print("\nVocabularul:")
print(vectorizer.get_feature_names_out())

# Afișarea scorurilor TF-IDF pentru fiecare categorie
print("\nScoruri TF-IDF:")
print(X.toarray())

import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

# Dacă nu ai descărcat deja stopwords, o poți face acum
nltk.download('stopwords')


# Creează vectorizatorul TF-IDF
tfidf_vectorizer = TfidfVectorizer(stop_words=nltk.corpus.stopwords.words('romanian'))

# Transformă corpusul într-o matrice TF-IDF
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)

# Vocabularul (termenii din corpus)
terms = tfidf_vectorizer.get_feature_names_out()

# Verifică scorurile TF-IDF pentru primul document
first_document_scores = tfidf_matrix[0].toarray()[0]

# Afișează scorurile și cuvintele corespunzătoare
sorted_indices = np.argsort(first_document_scores)[::-1]

# Afișează primele 10 scoruri cele mai mari pentru primul document
print("Cele mai importante 10 cuvinte din primul document:")
for index in sorted_indices[:10]:
    print(f"Termen: {terms[index]}, Scor TF-IDF: {first_document_scores[index]}")

# Căutăm scorul pentru un cuvânt specific (de exemplu "istorie")
word = 'istorie'  # Exemplu de cuvânt pe care vrei să-l verifici
if word in terms:
    index_of_word = terms.tolist().index(word)
    word_score = first_document_scores[index_of_word]
    print(f"\nScor TF-IDF pentru '{word}' : {word_score}")
else:
    print(f"\nCuvântul '{word}' nu există în vocabularul generat.")

"""### Bag of Words (BoW) cuvinte-cheie

transf cuvintele cheie in vectori si calculeaza similaritatea intre ceea ce introduce utilizatoru si cuvintele cheie
"""

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Textul utilizatorului
text_utilizator = "Sunt o fire pasionata de cultură, ador sa vad clădirile vechi"

# Cuvintele cheie pentru fiecare categorie
cuvinte_cheie = {
    "religion": ["religios", "spiritual", "biserică", "mănăstire", "credință"],
    "historic architecture": ["clădiri vechi", "monumente istorice", "istorie", "patrimoniu"],
    "cinemas": ["cinema", "film", "sală de cinema", "evenimente cinematografice"],
    "historic": ["istorie", "cultură", "evenimente istorice", "istorie"],
    "cultural": ["cultură", "arte", "expoziție", "festival", "evenimente culturale", "muzică", "dans"],
    "other": ["diverse", "locație", "interesant", "explorare", "necategorizat", "activități diverse"],
    "museums": ["muzeu", "expoziție", "artă", "istorie", "cultură"],
    "architecture": ["arhitectură", "design", "clădiri", "structuri", "construcții"],
    "fountains": ["fântână", "apă", "fontană", "loc de relaxare", "jocuri de apă"],
    "palaces": ["palat", "monarhie", "istorie", "eleganță", "lux"],
    "theatres and entertainments": ["teatru", "spectacol", "muzică", "dans", "entertainment", "divertisment", "cultură"],
    "towers": ["turn", "vârf", "panoramă", "priveliște"],
    "cemeteries": ["cemetery", "mormânt", "istorie", "cultură", "spiritualitate"],
    "biographical museums": ["muzeu biografic", "viața unui om"],
    "fortifications": ["fortificație", "castel", "cetate", "istorie"],
    "urban environment": ["urban", "oraș", "viață urbană"],
    "gardens and parks": ["grădina", "parc", "natură", "relaxare", "plimbare"],
    "view points": ["priveliște", "panoramă", "peisaj", "natură"],
    "science museums": ["muzeu stiințific", "inovație", "tehnologie", "descoperire", "experimente", "invenții"],
    "settlements": ["așezare", "comunitate", "village", "oraș", "istorie", "cultura locală"],
    "natural": ["natură", "conservare", "peisaj natural", "faţă", "floră"],
    "beaches": ["plajă", "soare", "vacanță", "relaxare", "mare", "ocean", "nisip", "natură"],
    "geological formations": ["forme geologice", "munte", "caverne", "peșteri", "natură"],
    "battlefields": ["câmp de bătălie", "istorie militară", "război", "istorie"],
    "bridges": ["pod", "construcție", "istorie"]
}

# Transformă textul utilizatorului și cuvintele cheie într-o listă de texte
texte_combinate = [text_utilizator] + [" ".join(keywords) for keywords in cuvinte_cheie.values()]

# Aplicarea CountVectorizer pentru a obține BoW
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texte_combinate)

# Calcularea similarității cosinus
similaritati = cosine_similarity(X[0:1], X[1:])

# Afișarea rezultatelor
for i, categorie in enumerate(cuvinte_cheie):
    print(f"Similaritatea utilizatorului cu categoria '{categorie}': {similaritati[0][i]:.4f}")

"""### One-Hot Encoding: sezon + tip calatorie+pret

transf din numere in text restul de coloane
"""

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np


# One-hot encoding pentru sezon
encoder_sezon = OneHotEncoder(sparse_output=False)
sezon_encoded = encoder_sezon.fit_transform(df[['sezon']])

# One-hot encoding pentru tipul de călătorie
encoder_tip_calatorie = OneHotEncoder(sparse_output=False)
tip_calatorie_encoded = encoder_tip_calatorie.fit_transform(df[['tip_calatorie']])

# One-hot encoding pentru preț
encoder_pret = OneHotEncoder(sparse_output=False)
pret_encoded = encoder_pret.fit_transform(df[['pret_categorie']])

# Crearea unui nou DataFrame cu codificările one-hot
df_sezon_encoded = pd.DataFrame(sezon_encoded, columns=encoder_sezon.categories_[0])
df_tip_calatorie_encoded = pd.DataFrame(tip_calatorie_encoded, columns=encoder_tip_calatorie.categories_[0])
df_pret_encoded = pd.DataFrame(pret_encoded, columns=encoder_pret.categories_[0])

# Adăugarea codificărilor la DataFrame-ul original
df = pd.concat([df, df_sezon_encoded, df_tip_calatorie_encoded, df_pret_encoded], axis=1)

# Eliminăm coloanele originale
df = df.drop(['sezon', 'tip_calatorie', 'pret_categorie'], axis=1)
df.head()

"""## Impartirea datelor in date de antrenare si testare

## Regresia logistica (tre sa refaci zona asta ca nu mere a ramas dupa alg tf-idf)
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# Cuvinte cheie pentru fiecare categorie
categorii = {
    "religion": ["religios", "spiritual", "biserică", "mănăstire", "credință"],
    "historic architecture": ["clădiri vechi", "monumente istorice", "istorie", "patrimoniu"],
    "cinemas": ["cinema", "film", "sală de cinema", "evenimente cinematografice"],
    "historic": ["istoric", "cultură", "evenimente istorice", "istorie"],
    "cultural": ["cultură", "arte", "expoziție", "festival", "evenimente culturale", "muzică", "dans"],
    "other": ["diverse", "locație", "interesant", "explorare", "necategorizat", "activități diverse"],
    "museums": ["muzeu", "expoziție", "artă", "istorie", "cultură"],
    "architecture": ["arhitectură", "design", "clădiri", "structuri", "construcții"],
    "fountains": ["fântână", "apă", "fontană", "loc de relaxare", "jocuri de apă"],
    "palaces": ["palat", "monarhie", "regal", "eleganță", "lux"],
    "theatres and entertainments": ["teatru", "spectacol", "muzică", "dans", "entertainment", "divertisment"],
    "towers": ["turn", "vârf", "panoramă", "priveliște"],
    "cemeteries": ["cemetery", "mormânt", "istorie", "cultură", "spiritualitate"],
    "biographical museums": ["muzeu biografic", "viața unui om"],
    "fortifications": ["fortificație", "castel", "cetate"],
    "urban environment": ["urban", "oraș", "străzi", "viață urbană"],
    "gardens and parks": ["grădina", "parc", "natură", "relaxare", "plimbare"],
    "view points": ["priveliște", "panoramă", "peisaj"],
    "science museums": ["muzeu științific", "inovație", "tehnologie", "descoperire", "experimente", "invenții"],
    "settlements": ["așezare", "comunitate", "village", "oraș", "istorie", "cultura locală"],
    "natural": ["natură", "conservare", "peisaj natural", "faună", "floră"],
    "beaches": ["plajă", "soare", "vacanță", "relaxare", "mare", "ocean", "nisip"],
    "geological formations": ["forme geologice", "munte", "caverne", "peșteri"],
    "battlefields": ["câmp de bătălie", "istorie militară", "război"],
    "bridges": ["pod", "construcție", "istoric"]
}


# Crearea vectorului TF-IDF
vectorizer = TfidfVectorizer(stop_words='english')  # Poți adăuga un set de stopwords personalizat dacă vrei
X = vectorizer.fit_transform(corpus)

# Etichetele corespunzătoare categoriilor
y = [i for i in range(len(categorii))]  # Fiecare categorie va primi un număr unic

# Împărțirea datelor în seturi de antrenament și testare
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Crearea și antrenarea modelului de regresie logistică
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predicții pe setul de test
y_pred = model.predict(X_test)

# Evaluarea performanței modelului
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred)}")

# Testarea modelului pe o descriere nouă
noua_descriere = ["Plajă cu nisip fin și apă cristalină"]
noua_descriere_tfidf = vectorizer.transform(noua_descriere)
pred = model.predict(noua_descriere_tfidf)

# Afișăm categoria prezisă
categorie_pred = list(categorii.keys())[pred[0]]
print(f"Categoria prezisă pentru descrierea nouă: {categorie_pred}")

"""# Predicția

### ~TF-IDF~
"""

from sklearn.metrics.pairwise import cosine_similarity

# Descrierea utilizatorului (exemplu)
descriere_utilizator = "imi place sa "

# Crearea vectorului TF-IDF pentru descrierea utilizatorului
X_utilizator = vectorizer.transform([descriere_utilizator])

# Calcularea similarității cosinus între descrierea utilizatorului și fiecare categorie
similaritati = cosine_similarity(X_utilizator, X)

# Găsirea categoriei cu cel mai mare scor
index_max = similaritati.argmax()
categorie_predicție = list(categorii.keys())[index_max]

print(f"Categoria recomandată pentru utilizator este: {categorie_predicție}")

"""# Generarea"""