# -*- coding: utf-8 -*-
"""Ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJZViJpCrDbthP6xBu2ZRKRKRrTVTtgC

Inceputuri

# Colectarea de date
"""

import requests
import pandas as pd
import time
import random

api_key = "5ae2e3f221c38a28845f05b6d39ea85b65163d209754a67b5f62156e"

orase = ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Constanta",
         "Brasov", "Oradea", "Sibiu", "Targu Mures", "Craiova", "Galati", "Suceava"]

toate_locatiile = []

for oras in orase:
    print(f"📍 Caut în {oras}")

    geo = requests.get(
        f"https://api.opentripmap.com/0.1/en/places/geoname?name={oras}&apikey={api_key}"
    ).json()

    lat, lon = geo.get("lat"), geo.get("lon")

    if not lat or not lon:
        print(f"⚠️ Nu am găsit coordonate pentru {oras}. Sar peste...")
        continue

    radius_url = f"https://api.opentripmap.com/0.1/en/places/radius?radius=10000&lon={lon}&lat={lat}&limit=100&apikey={api_key}"
    features = requests.get(radius_url).json().get("features", [])

    for f in features:
        xid = f["properties"]["xid"]
        detail_url = f"https://api.opentripmap.com/0.1/en/places/xid/{xid}?apikey={api_key}"
        detail = requests.get(detail_url).json()

        if not detail.get("name"):
            continue

        rate = detail.get("rate", "")
        popularitate = {"3h": 3, "2h": 2, "1h": 1}.get(rate, 0)

        rating_general = round(random.uniform(3.5, 5.0), 1)
        nr_recenzii = random.randint(50, 3000)

        categorii = detail.get("kinds", "")
        categorie = categorii.split(",")[0].replace("_", " ").capitalize() if categorii else "Necunoscut"
        categorie_lc = categorie.lower()

        # Sezon
        if "beaches" in categorie_lc or "coast" in categorie_lc:
            sezon = "Cald"
        elif "ski" in categorie_lc or "mountain" in categorie_lc:
            sezon = "Rece"
        elif "museum" in categorie_lc or "architecture" in categorie_lc:
            sezon = "Oricând"
        else:
            sezon = random.choice(["Cald", "Rece", "Oricând"])

        # Pret estimativ
        if "museum" in categorie_lc:
            pret = random.randint(20, 60)
        elif "amusement" in categorie_lc:
            pret = random.randint(50, 100)
        elif "thermal" in categorie_lc or "spa" in categorie_lc:
            pret = random.randint(70, 150)
        elif "park" in categorie_lc or "nature" in categorie_lc:
            pret = 0
        elif "religious" in categorie_lc or "monastery" in categorie_lc:
            pret = random.choice([0, 10])
        else:
            pret = random.randint(10, 50)

        if pret == 0:
            pret_categorie = "Gratuit"
        elif pret <= 30:
            pret_categorie = "Mic"
        elif pret <= 70:
            pret_categorie = "Mediu"
        else:
            pret_categorie = "Mare"

        # Tip calatorie
        if any(kw in categorie_lc for kw in ["museum", "architecture", "urban"]):
            tip_calatorie = "City Break"
        elif any(kw in categorie_lc for kw in ["park", "nature", "mountain", "lake"]):
            tip_calatorie = "Relaxare"
        elif any(kw in categorie_lc for kw in ["thermal", "spa", "amusement", "beach"]):
            tip_calatorie = "Relaxare"
        elif any(kw in categorie_lc for kw in ["historic", "religious", "monastery"]):
            tip_calatorie = "Circuit"
        else:
            tip_calatorie = random.choice(["City Break", "Circuit", "Relaxare"])

        # Durata minima (numerică)
        if tip_calatorie == "City Break":
            durata_minima = 1
        elif tip_calatorie == "Circuit":
            durata_minima = 5
        else:
            durata_minima = 2

        # Cuvinte cheie pentru locație
        cuvinte_cheie = []

        if "religion" in categorie_lc:
            cuvinte_cheie = ["religios", "spiritual", "biserică", "mănăstire", "credință",]
        elif "historic architecture" in categorie_lc:
            cuvinte_cheie = [ "clădiri vechi", "monumente istorice", "istorie", "patrimoniu"]
        elif "historic" in categorie_lc:
            cuvinte_cheie = ["istoric", "cultură", "evenimente istorice", "istorie"]
        elif "cinemas" in categorie_lc:
            cuvinte_cheie = ["cinema", "film",  "sală de cinema", "evenimente cinematografice"]
        elif "cultural" in categorie_lc:
            cuvinte_cheie = ["cultură", "arte", "expoziție", "festival", "evenimente culturale", "muzică", "dans"]
        elif "other" in categorie_lc:
            cuvinte_cheie = ["diverse", "locație", "interesant", "explorare", "necategorizat", "activități diverse"]
        elif "museums" in categorie_lc:
            cuvinte_cheie = ["muzeu", "expoziție", "artă", "istorie", "cultură"]
        elif "architecture" in categorie_lc:
            cuvinte_cheie = ["arhitectură", "design", "clădiri", "structuri", "construcții", ]
        elif "fountains" in categorie_lc:
            cuvinte_cheie = ["fântână", "apă", "fontană", "loc de relaxare", "jocuri de apă"]
        elif "palaces" in categorie_lc:
            cuvinte_cheie = ["palat", "monarhie", "regal", "eleganță", "lux"]
        elif "theatres and entertainments" in categorie_lc:
            cuvinte_cheie = ["teatru", "spectacol", "muzică", "dans", "entertainment", "divertisment"]
        elif "towers" in categorie_lc:
            cuvinte_cheie = ["turn", "vârf", "panoramă", "priveliște"]
        elif "cemeteries" in categorie_lc:
            cuvinte_cheie = ["cemetery", "mormânt", "istorie", "cultură", "spiritualitate"]
        elif "biographical museums" in categorie_lc:
            cuvinte_cheie = ["muzeu biografic", "viața unui om"]
        elif "fortifications" in categorie_lc:
            cuvinte_cheie = ["fortificație", "castel", "cetate"]
        elif "urban environment" in categorie_lc:
            cuvinte_cheie = ["urban", "oraș", "străzi", "viață urbană"]
        elif "gardens and parks" in categorie_lc:
            cuvinte_cheie = ["grădina", "parc", "natură", "relaxare", "plimbare"]
        elif "view points" in categorie_lc:
            cuvinte_cheie = ["priveliște", "panoramă", "peisaj"]
        elif "science museums" in categorie_lc:
            cuvinte_cheie = ["muzeu științific", "inovație", "tehnologie", "descoperire", "experimente", "invenții"]
        elif "settlements" in categorie_lc:
            cuvinte_cheie = ["așezare", "comunitate", "village", "oraș", "istorie", "cultura locală"]
        elif "natural" in categorie_lc:
            cuvinte_cheie = ["natură", "conservare", "peisaj natural", "faună", "floră"]
        elif "beaches" in categorie_lc:
            cuvinte_cheie = ["plajă", "soare", "vacanță", "relaxare", "mare", "ocean", "nisip"]
        elif "geological formations" in categorie_lc:
            cuvinte_cheie = ["forme geologice", "munte", "caverne", "peșteri"]
        elif "battlefields" in categorie_lc:
            cuvinte_cheie = ["câmp de bătălie", "istorie militară", "război"]
        elif "bridges" in categorie_lc:
            cuvinte_cheie = ["pod", "construcție", "istoric"]
        else:
            cuvinte_cheie = ["locație", "descoperire", "activități diverse"]

        location = {
            "oras": oras,
            "denumire": detail.get("name"),
            "categorie": categorie,
            "rating_general": rating_general,
            "nr_recenzii": nr_recenzii,
            "pret_categorie": pret_categorie,
            "sezon": sezon,
            "tip_calatorie": tip_calatorie,
            "durata_minima": durata_minima,
            "cuvinte_cheie": cuvinte_cheie,
        }
        toate_locatiile.append(location)
        time.sleep(1)  # Respectă limita de API (maxim 1 cerere pe secundă)

# Crează DataFrame din lista de locații
df_locatii = pd.DataFrame(toate_locatiile)

# Salvează în format CSV
df_locatii.to_csv("locatii_turistice.csv", index=False)

# Afișează primele 5 locații
print(df_locatii.head())

"""# Descrierea datelor"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("locatii_turistice.csv")
df.head()

print("Randuri: ", len(df), " Coloane:  ", len(df.columns))

print("Numar de elemente:", len(df['rating_general']))
print("Max: ",max(df['rating_general']))
print("Min: ",min(df['rating_general']))
print("Medie: ",df['rating_general'].mean())
print("Mediana:", df['rating_general'].median())
print("Varianta: ", df['rating_general'].std())

plt.hist(df['rating_general'])

"""# Normalizarea și preprocesarea datelor:

### Verifificarea si tratarea datelor null
"""

df.isnull().sum() #numar cate date sunt null

df=df.dropna()
df.isnull().sum()
# sterg datele nulll si verific daca mai am altele

"""## Tratarea duplicatelor"""

print(df.duplicated())  # Afișează un True pentru rândurile duplicate

"""## Standardizarea"""

print(df['categorie'].unique())  # Afișează valorile unice din coloana 'categorie'
print(df['tip_calatorie'].unique())  # Afișează valorile unice din coloana 'tip_calatorie'

"""## Detectarea și Tratarea Valorilor Aberante"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Calcularea IQR pentru coloana 'rating_general'
Q1 = df['rating_general'].quantile(0.25)
Q3 = df['rating_general'].quantile(0.75)
IQR = Q3 - Q1

# Definirea limitelor pentru valorile aberante
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Detectarea valorilor aberante
outliers = df[(df['rating_general'] < lower_bound) | (df['rating_general'] > upper_bound)]

print("Valorile aberante identificate:", outliers)

"""## Transformam String in Numere

### One-Hot Encoding: sezon + tip calatorie+pret
"""

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np


# One-hot encoding pentru sezon
encoder_sezon = OneHotEncoder(sparse_output=False)
sezon_encoded = encoder_sezon.fit_transform(df[['sezon']])

# One-hot encoding pentru tipul de călătorie
encoder_tip_calatorie = OneHotEncoder(sparse_output=False)
tip_calatorie_encoded = encoder_tip_calatorie.fit_transform(df[['tip_calatorie']])

# One-hot encoding pentru preț
encoder_pret = OneHotEncoder(sparse_output=False)
pret_encoded = encoder_pret.fit_transform(df[['pret_categorie']])

# Crearea unui nou DataFrame cu codificările one-hot
df_sezon_encoded = pd.DataFrame(sezon_encoded, columns=encoder_sezon.categories_[0])
df_tip_calatorie_encoded = pd.DataFrame(tip_calatorie_encoded, columns=encoder_tip_calatorie.categories_[0])
df_pret_encoded = pd.DataFrame(pret_encoded, columns=encoder_pret.categories_[0])

# Adăugarea codificărilor la DataFrame-ul original
df = pd.concat([df, df_sezon_encoded, df_tip_calatorie_encoded, df_pret_encoded], axis=1)

# Eliminăm coloanele originale
df = df.drop(['sezon', 'tip_calatorie', 'pret_categorie'], axis=1)
df.head()

"""### Bag of Words (BoW) cuvinte-cheie"""

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Descărcarea stopwords și wordnet din NLTK
nltk.download('stopwords')
nltk.download('wordnet')

# Inițializare pentru lemmatizare și stopwords
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('romanian'))

# Funcția de preprocesare a textului
def preprocess_text(text):
    # Conversia la litere mici
    text = text.lower()

    # Eliminarea semnelor de punctuație
    text = re.sub(r'[^\w\s]', '', text)

    # Eliminarea stopwords
    text = " ".join([word for word in text.split() if word not in stop_words])

    # Lemmatizarea
    text = " ".join([lemmatizer.lemmatize(word) for word in text.split()])

    return text

# Textul utilizatorului
text_utilizator = "istorie, cladiri vechi,eleganta, monarhie"

# Cuvintele cheie pentru fiecare categorie
cuvinte_cheie = {
    "religion": ["religios", "spiritual", "biserică", "mănăstire", "credință"],
    "historic architecture": ["clădiri vechi", "monumente istorice", "istorie", "patrimoniu"],
    "cinemas": ["cinema", "film", "sală de cinema", "evenimente cinematografice"],
    "historic": ["istorie", "cultură", "evenimente istorice", "istorie"],
    "cultural": ["cultură", "arte", "expoziție", "festival", "evenimente culturale", "muzică", "dans"],
    "other": ["diverse", "locație", "interesant", "explorare", "necategorizat", "activități diverse"],
    "museums": ["muzeu", "expoziție", "artă", "istorie", "cultură"],
    "architecture": ["arhitectură", "design", "clădiri", "structuri", "construcții"],
    "fountains": ["fântână", "apă", "fontană", "loc de relaxare", "jocuri de apă"],
    "palaces": ["palat", "monarhie", "istorie", "eleganță", "lux"],
    "theatres and entertainments": ["teatru", "spectacol", "muzică", "dans", "entertainment", "divertisment", "cultură"],
    "towers": ["turn", "vârf", "panoramă", "priveliște"],
    "cemeteries": ["cemetery", "mormânt", "istorie", "cultură", "spiritualitate"],
    "biographical museums": ["muzeu biografic", "viața unui om"],
    "fortifications": ["fortificație", "castel", "cetate", "istorie"],
    "urban environment": ["urban", "oraș", "viață urbană"],
    "gardens and parks": ["grădina", "parc", "natură", "relaxare", "plimbare"],
    "view points": ["priveliște", "panoramă", "peisaj", "natură"],
    "science museums": ["muzeu stiințific", "inovație", "tehnologie", "descoperire", "experimente", "invenții"],
    "settlements": ["așezare", "comunitate", "village", "oraș", "istorie", "cultura locală"],
    "natural": ["natură", "conservare", "peisaj natural", "faţă", "floră"],
    "beaches": ["plajă", "soare", "vacanță", "relaxare", "mare", "ocean", "nisip", "natură"],
    "geological formations": ["forme geologice", "munte", "caverne", "peșteri", "natură"],
    "battlefields": ["câmp de bătălie", "istorie militară", "război", "istorie"],
    "bridges": ["pod", "construcție", "istorie"]
}

# Preprocesarea textului utilizatorului
text_utilizator_preprocesat = preprocess_text(text_utilizator)

# Preprocesarea cuvintelor cheie pentru fiecare categorie
cuvinte_cheie_preprocesate = {categorie: preprocess_text(" ".join(keywords)) for categorie, keywords in cuvinte_cheie.items()}

# Transformă textul utilizatorului și cuvintele cheie într-o listă de texte
texte_combinate = [text_utilizator_preprocesat] + list(cuvinte_cheie_preprocesate.values())

# Aplicarea CountVectorizer pentru a obține BoW
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texte_combinate)

# Calcularea similarității cosinus
similaritati = cosine_similarity(X[0:1], X[1:])[0]

# Calcularea probabilității doar pentru similaritățile mai mari de 0.1
probabilitati = [
    round((similarity + 1) / 2, 2) if similarity > 0.1 else 0
    for similarity in similaritati
]

# Salvează probabilitățile într-un dicționar
# Dicționare separate pentru similaritate și probabilitate
similaritate_dict = {categorie: similaritate for categorie, similaritate in zip(cuvinte_cheie.keys(), similaritati)}
probabilitate_dict = {categorie: probabilitate for categorie, probabilitate in zip(cuvinte_cheie.keys(), probabilitati)}

# Afișăm dicționarele
print("Dicționarul de similarități:")
print(similaritate_dict)

print("Dicționarul de probabilități:")
print(probabilitate_dict)


# Afișarea rezultatelor
# Iterează prin dicționarele de similaritate și probabilitate
for categorie in similaritate_dict:
    similaritate = similaritate_dict[categorie]
    probabilitate = probabilitate_dict[categorie]

    # Afișează similaritatea și probabilitatea
    print(f"Similaritatea cu categoria '{categorie}' este {round(similaritate, 2)} (Probabilitate: {probabilitate * 100}%)")

"""## Adaugam coloanele : probabilitate, similaritate, preferinte"""

prag_preferinta=0.2
# Transformăm valorile din `categorie` și cheile dicționarelor în lowercase și eliminăm spațiile
df['categorie_clean'] = df['categorie'].str.strip().str.lower()

# Inițializăm coloanele 'similaritate', 'probabilitate' și 'preferinta' cu valori implicite
df['similaritate'] = 0
df['probabilitate'] = 0
df['preferinta'] = 0

# Verificăm valorile din df['categorie_clean'] pentru diagnostic
for i, cat in enumerate(df['categorie_clean']):
    # Verificăm dacă categoria se află în ambele dicționare
    if cat in similaritate_dict and cat in probabilitate_dict:
        # Obținem similaritatea și probabilitatea din dicționarele separate
        similaritate = similaritate_dict[cat]
        probabilitate = probabilitate_dict[cat]

        # Setăm valorile pentru similaritate și probabilitate
        df.at[i, 'similaritate'] = similaritate
        df.at[i, 'probabilitate'] = probabilitate

        # Setăm preferința pe baza pragului de probabilitate
        if probabilitate >= prag_preferinta:
            df.at[i, 'preferinta'] = 1  # Dacă probabilitatea este mai mare decât pragul, setăm 1
        else:
            df.at[i, 'preferinta'] = 0  # Dacă nu, setăm 0
    else:
        # Dacă categoria nu există în dicționare, lăsăm valorile implicite (0)
        df.at[i, 'similaritate'] = 0
        df.at[i, 'probabilitate'] = 0
        df.at[i, 'preferinta'] = 0

# Ștergem coloana temporară 'categorie_clean'
df.drop(columns=['categorie_clean'], inplace=True)

# Afișăm DataFrame-ul cu coloanele 'similaritate', 'probabilitate', și 'preferinta'
print(df)

"""### Creare Model+Predictie

### Random Forest
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split
import numpy as np

# Creăm un DataFrame pentru datele de antrenare
data = []
# Transformăm valorile din `categorie` și cheile dicționarelor în lowercase și eliminăm spațiile
df['categorie_clean'] = df['categorie'].str.strip().str.lower()
# Completăm datele cu valorile de similaritate și probabilitate
for cat in df['categorie_clean']:
    if cat in similaritate_dict and cat in probabilitate_dict:
        similaritate = similaritate_dict[cat]
        probabilitate = probabilitate_dict[cat]
        data.append([similaritate, probabilitate])
    else:
        data.append([0, 0])  # Dacă nu există, setăm la 0

# Creăm un DataFrame pentru datele de antrenare
train_df = pd.DataFrame(df, columns=['rating_general', 'similaritate', 'probabilitate'])

# Separăm datele în seturi de antrenare și testare
X = train_df[['similaritate', 'probabilitate']]  # Caracteristicile
y = train_df['rating_general']  # Eticheta (ratingul adevărat)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inițializăm modelul de Random Forest
model_rf = RandomForestRegressor(n_estimators=200, random_state=42)
model_rf.fit(X_train, y_train)

# Predicția pe setul de testare
y_pred_rf = model_rf.predict(X_test)

# Calculăm eroarea pătratică medie (MSE), R^2 și eroarea absolută medie (MAE)
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)
mae_rf = mean_absolute_error(y_test, y_pred_rf)

# Acuratețea: Procentajul de predicții care sunt la o diferență de maxim 0.5 față de valorile reale
acuratete_rf = np.mean(np.abs(y_test - y_pred_rf) <= 0.5) * 100  # Dacă diferența este sub 0.5

# Precizia: Procentajul de predicții corecte în raport cu predicțiile făcute
precizie_rf = np.mean(np.round(y_pred_rf) == np.round(y_test)) * 100  # Comparăm valorile rotunjite

# Afișăm rezultatele
print(f"Random Forest - Mean Squared Error (MSE): {mse_rf}")
print(f"Random Forest - R^2: {r2_rf}")
print(f"Random Forest - Mean Absolute Error (MAE): {mae_rf}")
print(f"Random Forest - Acuratețe: {acuratete_rf}%")
print(f"Random Forest - Precizie: {precizie_rf}%")

# Predicția ratingului pe setul original de date
df['rating_predicție_rf'] = model_rf.predict(X)

# Afișăm rezultatele finale
print(df[['categorie_clean', 'rating_predicție_rf']])

"""### Gradient Boosting Regressor"""

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split
import numpy as np

# Creăm un DataFrame pentru datele de antrenare
data = []
# Transformăm valorile din `categorie` și cheile dicționarelor în lowercase și eliminăm spațiile
df['categorie_clean'] = df['categorie'].str.strip().str.lower()
# Completăm datele cu valorile de similaritate și probabilitate
for cat in df['categorie_clean']:
    if cat in similaritate_dict and cat in probabilitate_dict:
        similaritate = similaritate_dict[cat]
        probabilitate = probabilitate_dict[cat]
        data.append([similaritate, probabilitate])
    else:
        data.append([0, 0])  # Dacă nu există, setăm la 0

# Creăm un DataFrame pentru datele de antrenare
train_df = pd.DataFrame(df, columns=['rating_general', 'similaritate', 'probabilitate'])

# Separăm datele în seturi de antrenare și testare
X = train_df[['similaritate', 'probabilitate']]  # Caracteristicile
y = train_df['rating_general']  # Eticheta (ratingul adevărat)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inițializăm modelul de Gradient Boosting Regressor
model_gb = GradientBoostingRegressor(n_estimators=100, random_state=42)
model_gb.fit(X_train, y_train)

# Predicția pe setul de testare
y_pred_gb = model_gb.predict(X_test)

# Calculăm eroarea pătratică medie (MSE), R^2 și eroarea absolută medie (MAE)
mse_gb = mean_squared_error(y_test, y_pred_gb)
r2_gb = r2_score(y_test, y_pred_gb)
mae_gb = mean_absolute_error(y_test, y_pred_gb)

# Acuratețea: Procentajul de predicții care sunt la o diferență de maxim 0.5 față de valorile reale
acuratete_gb = np.mean(np.abs(y_test - y_pred_gb) <= 0.5) * 100  # Dacă diferența este sub 0.5

# Precizia: Procentajul de predicții corecte în raport cu predicțiile făcute
precizie_gb = np.mean(np.round(y_pred_gb) == np.round(y_test)) * 100  # Comparăm valorile rotunjite

# Afișăm rezultatele
print(f"Gradient Boosting - Mean Squared Error (MSE): {mse_gb}")
print(f"Gradient Boosting - R^2: {r2_gb}")
print(f"Gradient Boosting - Mean Absolute Error (MAE): {mae_gb}")
print(f"Gradient Boosting - Acuratețe: {acuratete_gb}%")
print(f"Gradient Boosting - Precizie: {precizie_gb}%")

# Predicția ratingului pe setul original de date
df['rating_predicție_gb'] = model_gb.predict(X)

# Afișăm rezultatele finale
print(df[['categorie_clean', 'rating_predicție_gb']])